# Generated by Django 4.2.5 on 2023-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('demand', models.FloatField()),
                ('supply', models.FloatField()),
            ],
        ),
    ]
