# Generated by Django 4.2.5 on 2023-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_demand_predictionresult_demand_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_select', models.CharField(choices=[('Health and beauty', 'Health and Beauty'), ('Electronic accessories', 'Electronic Accessories'), ('Home and lifestyle', 'Home and Lifestyle')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
