# Generated by Django 4.2.5 on 2023-10-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_predictionresult2'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult2',
            name='input_image',
            field=models.ImageField(default='static/images/Demand_plot.jpg', upload_to='static/images/'),
        ),
    ]
