# Generated by Django 4.2.5 on 2023-10-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_predictionresult2_input_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictionresult2',
            old_name='input_image',
            new_name='Demand_Graph',
        ),
        migrations.AddField(
            model_name='predictionresult2',
            name='Demand_And_Supply_Graph',
            field=models.ImageField(default='static/images/DemandAndSupply_plot.jpg', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='predictionresult2',
            name='Dtree_Scatter_Graph',
            field=models.ImageField(default='static/images/dtree_scatter_plot.png', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='predictionresult2',
            name='Supply_Graph',
            field=models.ImageField(default='static/images/Supply_plot.jpg', upload_to='static/images/'),
        ),
    ]
