# Generated by Django 4.2.5 on 2023-10-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_predictionresult3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'permissions': [('view_prediction result', 'Can view prediction result')]},
        ),
    ]
