# Generated by Django 4.2.5 on 2023-10-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_predictionresult_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult2',
            options={'permissions': [('view_prediction result2', 'Can view prediction result')]},
        ),
        migrations.AlterModelOptions(
            name='predictionresult3',
            options={'permissions': [('view_prediction result3', 'Can view prediction result')]},
        ),
    ]
