# Generated by Django 4.2.5 on 2023-10-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_predictionresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'permissions': [('view_prediction result', 'Can view prediction result'), ('view_prediction result2', 'Can view prediction result2'), ('view_prediction result3', 'Can view prediction result3')]},
        ),
    ]
